### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by ha0ye** [weecology/project_template#2]
What does this project template need?
- [ ] basic file/folder structure
- [ ] demo README files
- [ ] instructions for basic usage (1-person)
- [ ] instructions for git/GitHub/collaboration
- [ ] instructions for eventual usage in papers/posters/slides
